create database db;
use db;
CREATE TABLE STUDENT (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO STUDENT VALUES (4243, 'Chirag');
INSERT INTO STUDENT VALUES (4211, 'Ravi');
INSERT INTO STUDENT VALUES (4215, 'Sourabh');
INSERT INTO STUDENT VALUES (4221, 'Gaurav');
